-- Bitbucket
CREATE USER bitbucket WITH ENCRYPTED PASSWORD 'bitbucket';
CREATE DATABASE bitbucket OWNER bitbucket;
GRANT ALL PRIVILEGES ON DATABASE bitbucket TO bitbucket;

-- Jira
CREATE USER jira WITH ENCRYPTED PASSWORD 'jira';
CREATE DATABASE jira OWNER jira;
GRANT ALL PRIVILEGES ON DATABASE jira TO jira;

-- Bamboo
CREATE USER bamboo WITH ENCRYPTED PASSWORD 'bamboo';
CREATE DATABASE bamboo OWNER bamboo;
GRANT ALL PRIVILEGES ON DATABASE bamboo TO bamboo;